#!/bin/bash

errexit()
{
  echo ""
  echo "$1"
  echo ""
  exit 1
}

usage()
{
  errexit "Usage: $0 imagefile [W95|Linux]"
}

if [ $(id -u) -ne 0 ]; then
  errexit "$0 must be run as root user"
fi

IMG="$1"
PART="$2"

if [ "${IMG}" = "" ]; then
  usage
fi

if [ ! -f "${IMG}" ]; then
  errexit "${IMG} not found"
fi

if [ "${PART}" = "" ]; then
  PART="Linux"
else
  PART="$(tr [A-Z] [a-z] <<< "${PART}")"
  if [ "${PART}" = "w95" ];then
    PART="W95"
  elif [ "${PART}" = "linux" ];then
    PART="Linux"
  else
    usage
  fi
fi

echo ""
echo -n "Check ${IMG} (y/n)? "
while read -r -n 1 -s answer; do
  if [[ "${answer}" = [yYnN] ]]; then
    echo "${answer}"
    if [[ "${answer}" = [yY] ]]; then
      break
    else
      errexit "Aborted"
    fi
  fi
done
echo ""

INFO="$(fdisk -lu "${IMG}")"
START="$(grep "${PART}" <<< "${INFO}" | awk '{print $2}')"
SIZE="$(grep "${PART}" <<< "${INFO}" | awk '{print $4}')"
LOOP="$(losetup -f --show -o $((${START} * 512)) --sizelimit $((${SIZE} * 512)) "${IMG}")"
if [ $? -ne 0 ]; then
  errexit "Unable to create BOOT loop device"
fi
FS_TYPE=$(blkid "${LOOP}" | sed -n 's|^.*TYPE="\(\S\+\)".*|\1|p')
if [ "${PART}" = "W95" ]; then
  dosfsck "${LOOP}"
else
  if [ "${FS_TYPE}" = "f2fs" ]; then
    fsck.f2fs "${LOOP}"
  else
    fsck.ext4 -f "${LOOP}"
  fi
fi
if [ $? -ne 0 ]; then
  losetup -d "${LOOP}"
  errexit "Filesystem appears corrupted"
fi
if [ "${FS_TYPE}" = "ext4" ]; then
  echo ""
  INFO="$(tune2fs -l "${LOOP}" 2>/dev/null)"
  echo "${INFO}"
fi
losetup -d "${LOOP}"
echo ""
